### ISSUE TITLE
Error File Fuzzing

### ISSUE THREAD

**Issue by Newpid0** [nccgroup/Zulu#1]
## New fuzzing session

Total fuzzcases = 1410880

---
## Fuzzpoint 0/22044, Testcase 0/63 Test type: format-strings, Test #0

"C:\Program Files (x86)\Adobe\Reader 10.0\Reader\AcroRd32.exe" "C:\Users\testadmin\Desktop\Zulu-master\tempfiles\temp0.pdf"
11:05:02   PID = 10868
11:05:02   Delay = 5.0
Traceback (most recent call last):
  File "zulu.py", line 3588, in StartFuzzing
    err = self.file_fuzzer(packet_data_list)
  File "zulu.py", line 1563, in file_fuzzer
    self.file_debugger(process.pid, self.process_run_time)
  File "zulu.py", line 1646, in file_debugger
    if win32.winerror(e) in (win32.ERROR_SEM_TIMEOUT, win32.WAIT_TIMEOUT):
AttributeError: 'module' object has no attribute 'winerror'

**Comment by slowcode42** [comment]
if win32.winerror(e) in (win32.ERROR_SEM_TIMEOUT, win32.WAIT_TIMEOUT):
↓
if e.winerror in (win32.ERROR_SEM_TIMEOUT, win32.WAIT_TIMEOUT):

**Comment by Newpid0** [comment]
That does it thanks!
